---
title: "percolation_network"
author: "RUI. GUO"
date: "2024-07-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Code for the percolation process on network
```{r}
library(igraph)
library(reshape2)
library(plyr)
library(rgdal)
```

```{r}
# We will use the London road network as an example

# Any other file containing the information of the network in the following format
# "id_node1","id_node2","link_weight" works
dir <- "../data/london_street_net/"
file_network <- paste0(dir,"London_edgelist_clean.txt")

# if the network is embedded in space we can get its coordinates as well to plot the network in space
file_coords <- paste0(dir,"london_coordinates_clean.csv")

#Now let us create the directory for the results
dir_res <- "Results/"
dir.create(dir_res)
#and the directory where you will create your membership tables
dir_memb <- paste0(dir_res,"membTables/")
dir.create(dir_memb)

#Files for the results:

    #number of clusters at each threshold
    file_n_clust <- paste0(dir_res,"n_clusters_p")

    #file for the largest cluster size
    file_clust_size <- paste0(dir_res,"clust_p_size.txt")

    #directory for the results of the subnetworks
    dir_nets <- paste0(dir_res,"net_measures/")
    dir.create(dir_nets)
    #let us define the function to be used later on to comute the topological diameter
    top_diameter <- function(g){
      diameter(g,weights = NA)
    }
    
#-----------------
```


#-----------------Network ----------------
```{r}
#let us read the file that contains the list of nodes
all_table <- read.table(file_network,header=T,sep=",")
head(all_table)
```

```{r}
#choose the column that contains the weight that you which to use for the percolation
colnames(all_table)

#In this case it's column 3, "length".
p_col=3
```

```{r}
#let us construct the network first and do the percolation afterwards
node1=all_table$start_point
node2=all_table$end_point
weight=all_table$length
df=data.frame(node1,node2,weight)

G=graph.data.frame(df,directed=FALSE)
summary(G)
head(E(G))
```

```{r}
# Let us see if there are self loops
sum(which_loop(G, eids = E(G)))
# yes, let us remove them
G=simplify(G, remove.loops = TRUE)
sum(which_loop(G, eids = E(G)))
```

```{r}
#Is it a connected network or does it have disconnected parts?
components(G)$no

summary(components(G))
#There are 135 disconnected components. 
```


```{r}
#This operation gives you the membership of each point, the cluster size of 
#each component is obtained by typing \$csize and the number of clusters \$no.

dist_sizes=components(G)$csize
sort(dist_sizes,decreasing=T)[1:20]
#The largest connected component has most points
```

```{r}
#Let us compute the size of largest component
largest_cpt=max(dist_sizes)
tot_nodes=length(V(G))
largest_cpt/tot_nodes
#Although there are disconnected bits, 99% of the nodes belong to the largest component.
```

```{r}
#Let us take only the largest connected component
gclust<-components(G, mode='weak')
largestConnectedComponent<-induced.subgraph(G, V(G)[which(gclust$membership == which.max(gclust$csize))])
G=largestConnectedComponent
summary(G)
all_weights=(E(G)$weight)
size_net=length(V(G))
```

```{r}
#--> let us assign coordinates to the nodes
data_coords <- read.csv(file_coords,sep=',',header=TRUE)
head(data_coords)
```


#-----------
```{r}
#project coords doesn't work ignore this bit
coords <- cbind(Easting = as.numeric(as.character(data_coords$x)),Northing = as.numeric(as.character(data_coords$y)))
head(coords)
```

```{r}
# we need to transform these coords to lat long
# Variables for holding the coordinate system types (see:
# http://www.epsg.org/ for details)
ukgrid = "+init=epsg:27700"
latlong = "+init=epsg:4326"
GP_SP <- SpatialPointsDataFrame(coords,data=data.frame(data_coords$id,data_coords$LSOA11CD),proj4string = CRS(ukgrid))
#Because GP_SP is now a Spatial Data Frame, we need to use head(GP_SP@data) to view content.
head(GP_SP@data)
head(GP_SP@coords)

# Convert from Eastings and Northings to Latitude and Longitude
GP_SP_LL <- spTransform(GP_SP, CRS(latlong))
# we also need to rename the columns
colnames(GP_SP_LL@coords)[colnames(GP_SP_LL@coords) == "Easting"] <- "Longitude"
colnames(GP_SP_LL@coords)[colnames(GP_SP_LL@coords) == "Northing"] <- "Latitude"
head(GP_SP_LL@coords)
coords_latLong=as.data.frame(GP_SP_LL@coords)
head(coords_latLong)

# head(GP_SP_LL)
# proj_coords= coords_latLong %>% st_as_sf(coords=1:2,crs=27700)
# st_is_longlat(proj_coords)
# set_as_sf(proj_coords,crs=27700)
# coords_london = st_set_crs(coords_latLong, 4326)

#plot(GP_SP_LL@coords)
vect_pos=match(V(G)$name,data_coords$id)
length(vect_pos)
head(vect_pos)
```

```{r}
V(G)$x=coords_latLong$Longitude[vect_pos]
V(G)$y=coords_latLong$Latitude[vect_pos]

summary(G)
# Viewing the properties of a graph node
vertex_attr_names(G)
```


```{r}
#let us plot it:
plot(G,vertex.label=NA,vertex.size=.01)
```


```{r}
#**************** this bit can be ignored *************************
#let us plot a subset
#just to have a sense, you can choose an initial threshold, here we had normalised data, so probabilities
new_G <- subgraph.edges(G, which((E(G)$weight) > 1500))
sub_weight=(E(new_G)$weight)
head(sub_weight)
max(sub_weight)
length(V(G))
length(V(new_G))
components(new_G)$no
# gclust_n<-components(new_G, mode='weak')
# new_Lcpt<-induced.subgraph(new_G, V(new_G)[which(gclust_n$membership == which.max(gclust_n$csize))])
# new_G=new_Lcpt
# sub_weight=(E(new_G)$weight)
length(V(G))
length(V(new_G))

palette_edges=hsv(h=1-((sub_weight/max(sub_weight)*2/3)+1/3),s = 1,v=1)

plot(new_G,vertex.size=.1,vertex.label=NA,edge.color=palette_edges)

#palette_edges_all=hsv(h=1-((all_weights/max(all_weights)*2/3)+1/3),s = 1,v=1)

#plot(G,vertex.size=.1,vertex.label=NA,edge.color=palette_edges_all)

#**************** end of bit that can be ignored *************************
```



```{r}
# define vector with percolation threshold
#"ID" "n_points"
#"1" 4801
#"2" 2
#"3" 2
rmin=5
rmax=3000
r0=seq(215, rmax,by=5)
n_loops=length(r0)
write('threshold\t size\t %total',file=file_clust_size,append = FALSE)

```

```{r}
#---------------
#define the colours for the 10 top clusters
top10 = colors()[c(553,29,258,654,91,115,456,48,102,40)]
#visualise the colours
barplot(c(1:10), col=top10)
jumps_2plot=c(50,100,300)
```

```{r}
#-------------------
for (i_t in r0)
{
  #i_t=50
  print(paste0("we are in loop=",i_t))
  #find subgraph such that all weights <= threshold r0
  g <- subgraph.edges(G, E(G)[weight<=i_t])
	#plot(g,vertex.label=NA,vertex.size=.01)
	
  #take subcomponents
	membclusters <- clusters(g, mode="weak")$membership
	m <- cbind(V(g)$name,membclusters)
	colnames(m) <- c("id_point","id_cluster")
	
	#let us compute the diameter of each of the subcomponents
	g_d<-decompose(g, mode = "weak",min.vertices = 4)
	n_v=sapply(g_d,vcount) #n. nodes
	d_v=sapply(g_d,diameter) #metric diameter
	d_top=sapply(g_d,top_diameter) #topological diameter
	m_d <- as.data.frame(cbind(n_v,d_v,d_top))
	head(m_d)
	m_d <-m_d[order(-m_d$n_v),]
	colnames(m_d)=c("n.nodes","diameter","topolDiameter")
	file_res_net <- paste0(dir_nets,"diameter",i_t,".txt")
	write.table(m_d,file_res_net,col.names = TRUE, sep=",",row.names=FALSE)
	
	#file for membership table for each threshold
	file_name <- paste0(dir_memb,"London_p")
	
	file_memb <- paste0(file_name,i_t,".txt")
	write.table(m,file_memb,col.names = TRUE, sep=",",row.names=FALSE)
	
	M_data <- as.data.frame(m)
	head(M_data)
	table_data <- table(M_data$id_cluster)
	tail(table_data)
	#Largest connected component
	LCC=max(unname(table_data))
	LCC_p=LCC/size_net
	v_LCC=c(i_t,LCC,LCC_p)
	if(i_t==rmin)
	{
	  v_LCC_t=v_LCC
	}else{
	  v_LCC_t=rbind(v_LCC_t,v_LCC)
	}
	
	sorted_table <- sort(table_data,decreasing = T)
	head(sorted_table)
	file_out <- paste(file_n_clust,i_t,".txt",sep="")
	write.table(sorted_table,file_out,row.names=FALSE,col.names=c('id_cluster','n_points'))
	
	#let us write the networks
	
	
	#let us construct at the same time the file with the largest cluster size, i.e. connected component.
	write(v_LCC,file=file_clust_size,append = TRUE)
	
	if(LCC>=(size_net*0.98))
	{
	  print(paste0("At threshold i_t=",i_t," LCC=",LCC," and size net=",size_net))
	  break
	}
```


```{r}
#-----------
# 	#plot the network
# 	if(i_t %in% jumps_2plot)
# 	{
# 	#plot the network
# 
# 	#Let us get the top 10 clusters
# 	list_clusts <- as.data.frame(sorted_table)
# 	colnames(list_clusts) <- c("id_cluster","n_points")
# 	head(list_clusts)
# 	list_clusts$colour = "grey"
# 	list_clusts$colour[1:10] = top10
# 	list_clusts$size = 0.01
# 	list_clusts$size[1:10] = 0.5
# 	list_clusts[1:20,]
# 	head(m)
# 	total_list <- merge(list_clusts,m,by="id_cluster")
# 	head(total_list)
# 
# 	# #let us put colour to the clusters
# 	# sub_list <- list_clusts[1:10,]
# 	# col_list <- merge(sub_list,m,by="id_cluster")
# 	# col_list[1:20,]
# 	# 
# 	# v=match(V(G)$name,as.character(col_list$id_point))
# 	# length(v)
# 	# v_pos_nn=which(!is.na(v))
# 	# length(v_pos_nn)
# 	# #V(G)[v_pos_nn]$name
# 	# V(G)$color="grey"
# 	# for(i_pos in 1:length(v_pos_nn))
# 	# {
# 	#   #we need to find 
# 	#   #i_pos=2
# 	#   print(paste0("i_pos=",i_pos))
# 	#   tmp_data=total_list[total_list$id_point==V(G)[v_pos_nn[i_pos]]$name,]
# 	#   V(G)[v_pos_nn[i_pos]]$color=tmp_data$colour
# 	# }
# 	# V(G)[v_pos_nn]$color
# 	# 
# 	# #total n. of clusters
# 	# d_clusts=length(list_clusts$id_cluster)
# 	# if(d_clusts<=10)
# 	# {
# 	#   #assign colours to top 15
# 	#   total_list$colour=top15[1:d_clusts]
# 	#   
# 	#   v=match(V(g)$name,as.character(sort_comp_tree$tree_ID))
# 	#   v_pos_nn=which(!is.na(v))
# 	#   V(g_tree)[v_pos_nn]$name
# 	#   for(i_pos in 1:length(v_pos_nn))
# 	#   {
# 	#     #we need to find 
# 	#     #i_pos=1
# 	#     tmp_data=sort_comp_tree[sort_comp_tree$tree_ID==V(g_tree)[v_pos_nn[i_pos]]$name,]
# 	#     V(g_tree)[v_pos_nn[i_pos]]$nfirms=tmp_data$n
# 	#     V(g_tree)[v_pos_nn[i_pos]]$colour=tmp_data$colour
# 	#   }
# 	#   V(g_tree)[v_pos_nn]$nfirms
# 	#   V(g_tree)[v_pos_nn]$colour
# 	# }else{
# 	#   #take only the top 15 from data
# 	#   sub_sort=sort_comp_tree[1:15,]
# 	#   sub_sort$colour=top15
# 	#   
# 	#   v=match(V(g_tree)$name,as.character(sub_sort$tree_ID))
# 	#   v_pos_nn=which(!is.na(v))
# 	#   V(g_tree)[v_pos_nn]$name
# 	#   for(i_pos in 1:length(v_pos_nn))
# 	#   {
# 	#     #we need to find 
# 	#     #i_pos=2
# 	#     tmp_data=sub_sort[sub_sort$tree_ID==V(g_tree)[v_pos_nn[i_pos]]$name,]
# 	#     V(g_tree)[v_pos_nn[i_pos]]$nfirms=tmp_data$n
# 	#     V(g_tree)[v_pos_nn[i_pos]]$colour=tmp_data$colour
# 	#   }
# 	#   V(g_tree)[v_pos_nn]$nfirms
# 	#   V(g_tree)[v_pos_nn]$colour
# 	#   
# 	# }
# 	# 
# # 
# 	#cosa nueva que deberia de funcionar
# 	V(G)$color <- ifelse(V(G)$name %in% as.character(total_list$id_point), total_list$colour,"grey")
# 	V(G)$size <- ifelse(V(G)$name %in% total_list$id_point, total_list$size,0.01)
# 	head(V(G)$color)
# 	plot.igraph(G,vertex.label=NA,vertex.frame.color=NA)
# 	}
	
}
```



```{r}
#Let us visualise the largest connected component
plot(v_LCC_t[,1],v_LCC_t[,2],xlab="distance",ylab="size",pch=16,cex=0.5,panel.first=grid())
plot(v_LCC_t[,1],v_LCC_t[,3],xlab="distance",ylab="size",pch=16,cex=0.5,panel.first=grid())
```



